// Code generated by goctl. DO NOT EDIT.
// Source: judge.proto

package server

import (
	"context"

	"zerooj/service/judge/internal/logic/judge"
	"zerooj/service/judge/internal/svc"
	"zerooj/service/judge/pb/judge"
)

type JudgeServer struct {
	svcCtx *svc.ServiceContext
	judge.UnimplementedJudgeServer
}

func NewJudgeServer(svcCtx *svc.ServiceContext) *JudgeServer {
	return &JudgeServer{
		svcCtx: svcCtx,
	}
}

// 测评
func (s *JudgeServer) Judge(ctx context.Context, in *judge.JudgeReq) (*judge.JudgeResp, error) {
	l := judgelogic.NewJudgeLogic(ctx, s.svcCtx)
	return l.Judge(in)
}
