// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: authenticate.proto

package authenticate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyMailCheckCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 验证码存储在redis中的key
	RedisKey string `protobuf:"bytes,1,opt,name=redisKey,proto3" json:"redisKey,omitempty"`
	// 用户输入的验证码
	CheckCode string `protobuf:"bytes,2,opt,name=checkCode,proto3" json:"checkCode,omitempty"`
}

func (x *VerifyMailCheckCodeReq) Reset() {
	*x = VerifyMailCheckCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyMailCheckCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMailCheckCodeReq) ProtoMessage() {}

func (x *VerifyMailCheckCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_authenticate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMailCheckCodeReq.ProtoReflect.Descriptor instead.
func (*VerifyMailCheckCodeReq) Descriptor() ([]byte, []int) {
	return file_authenticate_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyMailCheckCodeReq) GetRedisKey() string {
	if x != nil {
		return x.RedisKey
	}
	return ""
}

func (x *VerifyMailCheckCodeReq) GetCheckCode() string {
	if x != nil {
		return x.CheckCode
	}
	return ""
}

type VerifyMailCheckCodeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VerifyMailCheckCodeResp) Reset() {
	*x = VerifyMailCheckCodeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyMailCheckCodeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyMailCheckCodeResp) ProtoMessage() {}

func (x *VerifyMailCheckCodeResp) ProtoReflect() protoreflect.Message {
	mi := &file_authenticate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyMailCheckCodeResp.ProtoReflect.Descriptor instead.
func (*VerifyMailCheckCodeResp) Descriptor() ([]byte, []int) {
	return file_authenticate_proto_rawDescGZIP(), []int{1}
}

type FinishMailCheckReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 验证码存储在redis中的key
	RedisKey string `protobuf:"bytes,1,opt,name=redisKey,proto3" json:"redisKey,omitempty"`
}

func (x *FinishMailCheckReq) Reset() {
	*x = FinishMailCheckReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishMailCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMailCheckReq) ProtoMessage() {}

func (x *FinishMailCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_authenticate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMailCheckReq.ProtoReflect.Descriptor instead.
func (*FinishMailCheckReq) Descriptor() ([]byte, []int) {
	return file_authenticate_proto_rawDescGZIP(), []int{2}
}

func (x *FinishMailCheckReq) GetRedisKey() string {
	if x != nil {
		return x.RedisKey
	}
	return ""
}

type FinishMailCheckResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FinishMailCheckResp) Reset() {
	*x = FinishMailCheckResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authenticate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FinishMailCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishMailCheckResp) ProtoMessage() {}

func (x *FinishMailCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_authenticate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishMailCheckResp.ProtoReflect.Descriptor instead.
func (*FinishMailCheckResp) Descriptor() ([]byte, []int) {
	return file_authenticate_proto_rawDescGZIP(), []int{3}
}

var File_authenticate_proto protoreflect.FileDescriptor

var file_authenticate_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x22, 0x52, 0x0a, 0x16, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4d, 0x61, 0x69, 0x6c,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x65, 0x64, 0x69, 0x73, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x64, 0x69, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79,
	0x4d, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x30, 0x0a, 0x12, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x69, 0x6c, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x69, 0x73,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x64, 0x69, 0x73,
	0x4b, 0x65, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x69,
	0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x32, 0xcb, 0x01, 0x0a, 0x0d, 0x4d,
	0x61, 0x69, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x62, 0x0a, 0x13,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x24, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x25, 0x2e, 0x61, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4d,
	0x61, 0x69, 0x6c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x56, 0x0a, 0x0f, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x12, 0x20, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x2e, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4d, 0x61, 0x69, 0x6c, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x61, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_authenticate_proto_rawDescOnce sync.Once
	file_authenticate_proto_rawDescData = file_authenticate_proto_rawDesc
)

func file_authenticate_proto_rawDescGZIP() []byte {
	file_authenticate_proto_rawDescOnce.Do(func() {
		file_authenticate_proto_rawDescData = protoimpl.X.CompressGZIP(file_authenticate_proto_rawDescData)
	})
	return file_authenticate_proto_rawDescData
}

var file_authenticate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_authenticate_proto_goTypes = []any{
	(*VerifyMailCheckCodeReq)(nil),  // 0: authenticate.VerifyMailCheckCodeReq
	(*VerifyMailCheckCodeResp)(nil), // 1: authenticate.VerifyMailCheckCodeResp
	(*FinishMailCheckReq)(nil),      // 2: authenticate.FinishMailCheckReq
	(*FinishMailCheckResp)(nil),     // 3: authenticate.FinishMailCheckResp
}
var file_authenticate_proto_depIdxs = []int32{
	0, // 0: authenticate.MailCheckCode.VerifyMailCheckCode:input_type -> authenticate.VerifyMailCheckCodeReq
	2, // 1: authenticate.MailCheckCode.FinishMailCheck:input_type -> authenticate.FinishMailCheckReq
	1, // 2: authenticate.MailCheckCode.VerifyMailCheckCode:output_type -> authenticate.VerifyMailCheckCodeResp
	3, // 3: authenticate.MailCheckCode.FinishMailCheck:output_type -> authenticate.FinishMailCheckResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authenticate_proto_init() }
func file_authenticate_proto_init() {
	if File_authenticate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authenticate_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyMailCheckCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authenticate_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*VerifyMailCheckCodeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authenticate_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*FinishMailCheckReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authenticate_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*FinishMailCheckResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authenticate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authenticate_proto_goTypes,
		DependencyIndexes: file_authenticate_proto_depIdxs,
		MessageInfos:      file_authenticate_proto_msgTypes,
	}.Build()
	File_authenticate_proto = out.File
	file_authenticate_proto_rawDesc = nil
	file_authenticate_proto_goTypes = nil
	file_authenticate_proto_depIdxs = nil
}
