// Code generated by goctl. DO NOT EDIT.
// Source: problemset.proto

package judgedata

import (
	"context"

	"zerooj/service/problemset/pb/problemset"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddExampleReq          = problemset.AddExampleReq
	AddExampleResp         = problemset.AddExampleResp
	AddHintReq             = problemset.AddHintReq
	AddHintResp            = problemset.AddHintResp
	AddJudgeDataReq        = problemset.AddJudgeDataReq
	AddJudgeDataResp       = problemset.AddJudgeDataResp
	AddProblemReq          = problemset.AddProblemReq
	AddProblemResp         = problemset.AddProblemResp
	AddTagsReq             = problemset.AddTagsReq
	AddTagsResp            = problemset.AddTagsResp
	DeleteExampleReq       = problemset.DeleteExampleReq
	DeleteExampleResp      = problemset.DeleteExampleResp
	DeleteHintReq          = problemset.DeleteHintReq
	DeleteHintResp         = problemset.DeleteHintResp
	DeleteJudgeDataReq     = problemset.DeleteJudgeDataReq
	DeleteJudgeDataResp    = problemset.DeleteJudgeDataResp
	DeleteProblemReq       = problemset.DeleteProblemReq
	DeleteProblemResp      = problemset.DeleteProblemResp
	DeleteTagsReq          = problemset.DeleteTagsReq
	DeleteTagsResp         = problemset.DeleteTagsResp
	ExampleInfo            = problemset.ExampleInfo
	GetAllTagsReq          = problemset.GetAllTagsReq
	GetAllTagsResp         = problemset.GetAllTagsResp
	GetExampleReq          = problemset.GetExampleReq
	GetExampleResp         = problemset.GetExampleResp
	GetHintReq             = problemset.GetHintReq
	GetHintResp            = problemset.GetHintResp
	GetJudgeDataReq        = problemset.GetJudgeDataReq
	GetJudgeDataResp       = problemset.GetJudgeDataResp
	GetProblemContentReq   = problemset.GetProblemContentReq
	GetProblemContentResp  = problemset.GetProblemContentResp
	GetProblemExamplesReq  = problemset.GetProblemExamplesReq
	GetProblemExamplesResp = problemset.GetProblemExamplesResp
	GetProblemHintsReq     = problemset.GetProblemHintsReq
	GetProblemHintsResp    = problemset.GetProblemHintsResp
	GetProblemTagsReq      = problemset.GetProblemTagsReq
	GetProblemTagsResp     = problemset.GetProblemTagsResp
	HintInfo               = problemset.HintInfo
	JudgeDataInfo          = problemset.JudgeDataInfo
	MustDeleteTagsReq      = problemset.MustDeleteTagsReq
	MustDeleteTagsResp     = problemset.MustDeleteTagsResp
	ProblemAddTagsReq      = problemset.ProblemAddTagsReq
	ProblemAddTagsResp     = problemset.ProblemAddTagsResp
	ProblemDeleteTagsReq   = problemset.ProblemDeleteTagsReq
	ProblemDeleteTagsResp  = problemset.ProblemDeleteTagsResp
	SearchProblemReq       = problemset.SearchProblemReq
	SearchProblemResp      = problemset.SearchProblemResp
	TagInfo                = problemset.TagInfo
	UpdateExampleReq       = problemset.UpdateExampleReq
	UpdateExampleResp      = problemset.UpdateExampleResp
	UpdateHintReq          = problemset.UpdateHintReq
	UpdateHintResp         = problemset.UpdateHintResp
	UpdateJudgeDataReq     = problemset.UpdateJudgeDataReq
	UpdateJudgeDataResp    = problemset.UpdateJudgeDataResp
	UpdateProblemReq       = problemset.UpdateProblemReq
	UpdateProblemResp      = problemset.UpdateProblemResp
	UpdateTagsReq          = problemset.UpdateTagsReq
	UpdateTagsResp         = problemset.UpdateTagsResp

	JudgeData interface {
		// 添加测评数据，客服权限
		AddJudgeData(ctx context.Context, in *AddJudgeDataReq, opts ...grpc.CallOption) (*AddJudgeDataResp, error)
		// 删除测评数据，客服权限
		DeleteJudgeData(ctx context.Context, in *DeleteJudgeDataReq, opts ...grpc.CallOption) (*DeleteJudgeDataResp, error)
		// 修改测评数据，客服权限
		UpdateJudgeData(ctx context.Context, in *UpdateJudgeDataReq, opts ...grpc.CallOption) (*UpdateJudgeDataResp, error)
		// 获取题目的测评数据，返回minio对象名称，可缓存
		GetJudgeData(ctx context.Context, in *GetJudgeDataReq, opts ...grpc.CallOption) (*GetJudgeDataResp, error)
	}

	defaultJudgeData struct {
		cli zrpc.Client
	}
)

func NewJudgeData(cli zrpc.Client) JudgeData {
	return &defaultJudgeData{
		cli: cli,
	}
}

// 添加测评数据，客服权限
func (m *defaultJudgeData) AddJudgeData(ctx context.Context, in *AddJudgeDataReq, opts ...grpc.CallOption) (*AddJudgeDataResp, error) {
	client := problemset.NewJudgeDataClient(m.cli.Conn())
	return client.AddJudgeData(ctx, in, opts...)
}

// 删除测评数据，客服权限
func (m *defaultJudgeData) DeleteJudgeData(ctx context.Context, in *DeleteJudgeDataReq, opts ...grpc.CallOption) (*DeleteJudgeDataResp, error) {
	client := problemset.NewJudgeDataClient(m.cli.Conn())
	return client.DeleteJudgeData(ctx, in, opts...)
}

// 修改测评数据，客服权限
func (m *defaultJudgeData) UpdateJudgeData(ctx context.Context, in *UpdateJudgeDataReq, opts ...grpc.CallOption) (*UpdateJudgeDataResp, error) {
	client := problemset.NewJudgeDataClient(m.cli.Conn())
	return client.UpdateJudgeData(ctx, in, opts...)
}

// 获取题目的测评数据，返回minio对象名称，可缓存
func (m *defaultJudgeData) GetJudgeData(ctx context.Context, in *GetJudgeDataReq, opts ...grpc.CallOption) (*GetJudgeDataResp, error) {
	client := problemset.NewJudgeDataClient(m.cli.Conn())
	return client.GetJudgeData(ctx, in, opts...)
}
