// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"zerooj/service/user/internal/logic/registerlogin"
	"zerooj/service/user/internal/svc"
	"zerooj/service/user/pb/user"
)

type RegisterLoginServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedRegisterLoginServer
}

func NewRegisterLoginServer(svcCtx *svc.ServiceContext) *RegisterLoginServer {
	return &RegisterLoginServer{
		svcCtx: svcCtx,
	}
}

// 用户注册
func (s *RegisterLoginServer) UserRegister(ctx context.Context, in *user.UserRegisterReq) (*user.UserRegisterResp, error) {
	l := registerloginlogic.NewUserRegisterLogic(ctx, s.svcCtx)
	return l.UserRegister(in)
}

// 用户登录
func (s *RegisterLoginServer) UserLogin(ctx context.Context, in *user.UserLoginReq) (*user.UserLoginResp, error) {
	l := registerloginlogic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}
