// Code generated by goctl. DO NOT EDIT.
// Source: problemset.proto

package server

import (
	"context"

	"zerooj/service/problemset/internal/logic/problem"
	"zerooj/service/problemset/internal/svc"
	"zerooj/service/problemset/pb/problemset"
)

type ProblemServer struct {
	svcCtx *svc.ServiceContext
	problemset.UnimplementedProblemServer
}

func NewProblemServer(svcCtx *svc.ServiceContext) *ProblemServer {
	return &ProblemServer{
		svcCtx: svcCtx,
	}
}

// 添加问题
func (s *ProblemServer) AddProblem(stream problemset.Problem_AddProblemServer) error {
	l := problemlogic.NewAddProblemLogic(stream.Context(), s.svcCtx)
	return l.AddProblem(stream)
}

// 删除问题
func (s *ProblemServer) DeleteProblem(ctx context.Context, in *problemset.DeleteProblemReq) (*problemset.DeleteProblemResp, error) {
	l := problemlogic.NewDeleteProblemLogic(ctx, s.svcCtx)
	return l.DeleteProblem(in)
}

// 获取问题信息，可缓存
func (s *ProblemServer) GetProblemContent(in *problemset.GetProblemContentReq, stream problemset.Problem_GetProblemContentServer) error {
	l := problemlogic.NewGetProblemContentLogic(stream.Context(), s.svcCtx)
	return l.GetProblemContent(in, stream)
}

// 更新问题
func (s *ProblemServer) UpdateProblem(stream problemset.Problem_UpdateProblemServer) error {
	l := problemlogic.NewUpdateProblemLogic(stream.Context(), s.svcCtx)
	return l.UpdateProblem(stream)
}

// 分页搜索题目
func (s *ProblemServer) SearchProblem(ctx context.Context, in *problemset.SearchProblemReq) (*problemset.SearchProblemResp, error) {
	l := problemlogic.NewSearchProblemLogic(ctx, s.svcCtx)
	return l.SearchProblem(in)
}
