// Code generated by goctl. DO NOT EDIT.
// Source: authenticate.proto

package server

import (
	"context"

	"zerooj/service/authenticate/internal/logic/mailcheckcode"
	"zerooj/service/authenticate/internal/svc"
	"zerooj/service/authenticate/pb/authenticate"
)

type MailCheckCodeServer struct {
	svcCtx *svc.ServiceContext
	authenticate.UnimplementedMailCheckCodeServer
}

func NewMailCheckCodeServer(svcCtx *svc.ServiceContext) *MailCheckCodeServer {
	return &MailCheckCodeServer{
		svcCtx: svcCtx,
	}
}

// 校验
func (s *MailCheckCodeServer) VerifyMailCheckCode(ctx context.Context, in *authenticate.VerifyMailCheckCodeReq) (*authenticate.VerifyMailCheckCodeResp, error) {
	l := mailcheckcodelogic.NewVerifyMailCheckCodeLogic(ctx, s.svcCtx)
	return l.VerifyMailCheckCode(in)
}

// 邮箱验证码校验完毕
func (s *MailCheckCodeServer) FinishMailCheck(ctx context.Context, in *authenticate.FinishMailCheckReq) (*authenticate.FinishMailCheckResp, error) {
	l := mailcheckcodelogic.NewFinishMailCheckLogic(ctx, s.svcCtx)
	return l.FinishMailCheck(in)
}
