// Code generated by goctl. DO NOT EDIT.
// Source: problemset.proto

package server

import (
	"context"

	"zerooj/service/problemset/internal/logic/example"
	"zerooj/service/problemset/internal/svc"
	"zerooj/service/problemset/pb/problemset"
)

type ExampleServer struct {
	svcCtx *svc.ServiceContext
	problemset.UnimplementedExampleServer
}

func NewExampleServer(svcCtx *svc.ServiceContext) *ExampleServer {
	return &ExampleServer{
		svcCtx: svcCtx,
	}
}

// 添加样例
func (s *ExampleServer) AddExample(stream problemset.Example_AddExampleServer) error {
	l := examplelogic.NewAddExampleLogic(stream.Context(), s.svcCtx)
	return l.AddExample(stream)
}

// 删除样例
func (s *ExampleServer) DeleteExample(ctx context.Context, in *problemset.DeleteExampleReq) (*problemset.DeleteExampleResp, error) {
	l := examplelogic.NewDeleteExampleLogic(ctx, s.svcCtx)
	return l.DeleteExample(in)
}

// 修改样例
func (s *ExampleServer) UpdateExample(stream problemset.Example_UpdateExampleServer) error {
	l := examplelogic.NewUpdateExampleLogic(stream.Context(), s.svcCtx)
	return l.UpdateExample(stream)
}

// 获取样例
func (s *ExampleServer) GetExample(in *problemset.GetExampleReq, stream problemset.Example_GetExampleServer) error {
	l := examplelogic.NewGetExampleLogic(stream.Context(), s.svcCtx)
	return l.GetExample(in, stream)
}

// 获取题目的所有样例
func (s *ExampleServer) GetProblemExamples(in *problemset.GetProblemExamplesReq, stream problemset.Example_GetProblemExamplesServer) error {
	l := examplelogic.NewGetProblemExamplesLogic(stream.Context(), s.svcCtx)
	return l.GetProblemExamples(in, stream)
}
