// Code generated by goctl. DO NOT EDIT.
// Source: problemset.proto

package hint

import (
	"context"

	"zerooj/service/problemset/pb/problemset"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddExampleReq              = problemset.AddExampleReq
	AddExampleResp             = problemset.AddExampleResp
	AddHintReq                 = problemset.AddHintReq
	AddHintResp                = problemset.AddHintResp
	AddJudgeDataReq            = problemset.AddJudgeDataReq
	AddJudgeDataResp           = problemset.AddJudgeDataResp
	AddLanguageReq             = problemset.AddLanguageReq
	AddLanguageResp            = problemset.AddLanguageResp
	AddProblemReq              = problemset.AddProblemReq
	AddProblemResp             = problemset.AddProblemResp
	AddTagReq                  = problemset.AddTagReq
	AddTagResp                 = problemset.AddTagResp
	DeleteExampleReq           = problemset.DeleteExampleReq
	DeleteExampleResp          = problemset.DeleteExampleResp
	DeleteHintReq              = problemset.DeleteHintReq
	DeleteHintResp             = problemset.DeleteHintResp
	DeleteJudgeDataReq         = problemset.DeleteJudgeDataReq
	DeleteJudgeDataResp        = problemset.DeleteJudgeDataResp
	DeleteLanguageReq          = problemset.DeleteLanguageReq
	DeleteLanguageResp         = problemset.DeleteLanguageResp
	DeleteProblemReq           = problemset.DeleteProblemReq
	DeleteProblemResp          = problemset.DeleteProblemResp
	DeleteTagReq               = problemset.DeleteTagReq
	DeleteTagResp              = problemset.DeleteTagResp
	ExampleInfo                = problemset.ExampleInfo
	GetAllTagsReq              = problemset.GetAllTagsReq
	GetAllTagsResp             = problemset.GetAllTagsResp
	GetExampleReq              = problemset.GetExampleReq
	GetExampleResp             = problemset.GetExampleResp
	GetHintReq                 = problemset.GetHintReq
	GetHintResp                = problemset.GetHintResp
	GetJudgeDataReq            = problemset.GetJudgeDataReq
	GetJudgeDataResp           = problemset.GetJudgeDataResp
	GetLanguageByIdReq         = problemset.GetLanguageByIdReq
	GetLanguageByIdResp        = problemset.GetLanguageByIdResp
	GetLanguagesReq            = problemset.GetLanguagesReq
	GetLanguagesResp           = problemset.GetLanguagesResp
	GetProblemContentReq       = problemset.GetProblemContentReq
	GetProblemContentResp      = problemset.GetProblemContentResp
	GetProblemExamplesReq      = problemset.GetProblemExamplesReq
	GetProblemExamplesResp     = problemset.GetProblemExamplesResp
	GetProblemHintsReq         = problemset.GetProblemHintsReq
	GetProblemHintsResp        = problemset.GetProblemHintsResp
	GetProblemLanguagesReq     = problemset.GetProblemLanguagesReq
	GetProblemLanguagesResp    = problemset.GetProblemLanguagesResp
	GetProblemSubmitCountReq   = problemset.GetProblemSubmitCountReq
	GetProblemSubmitCountResp  = problemset.GetProblemSubmitCountResp
	GetProblemTagsReq          = problemset.GetProblemTagsReq
	GetProblemTagsResp         = problemset.GetProblemTagsResp
	GetSubmitByIdReq           = problemset.GetSubmitByIdReq
	GetSubmitByIdResp          = problemset.GetSubmitByIdResp
	GetUserProblemSubmitReq    = problemset.GetUserProblemSubmitReq
	GetUserProblemSubmitResp   = problemset.GetUserProblemSubmitResp
	GetUserSubmitReq           = problemset.GetUserSubmitReq
	GetUserSubmitResp          = problemset.GetUserSubmitResp
	HintInfo                   = problemset.HintInfo
	JudgeDataInfo              = problemset.JudgeDataInfo
	LanguageInfo               = problemset.LanguageInfo
	MustDeleteTagReq           = problemset.MustDeleteTagReq
	MustDeleteTagResp          = problemset.MustDeleteTagResp
	ProblemAddLanguagesReq     = problemset.ProblemAddLanguagesReq
	ProblemAddLanguagesResp    = problemset.ProblemAddLanguagesResp
	ProblemAddTagsReq          = problemset.ProblemAddTagsReq
	ProblemAddTagsResp         = problemset.ProblemAddTagsResp
	ProblemDeleteLanguagesReq  = problemset.ProblemDeleteLanguagesReq
	ProblemDeleteLanguagesResp = problemset.ProblemDeleteLanguagesResp
	ProblemDeleteTagsReq       = problemset.ProblemDeleteTagsReq
	ProblemDeleteTagsResp      = problemset.ProblemDeleteTagsResp
	ProblemInfo                = problemset.ProblemInfo
	ProblemLanguagesModel      = problemset.ProblemLanguagesModel
	SearchProblemReq           = problemset.SearchProblemReq
	SearchProblemResp          = problemset.SearchProblemResp
	SubmitCodeReq              = problemset.SubmitCodeReq
	SubmitCodeResp             = problemset.SubmitCodeResp
	SubmitInfo                 = problemset.SubmitInfo
	TagInfo                    = problemset.TagInfo
	UpdateExampleReq           = problemset.UpdateExampleReq
	UpdateExampleResp          = problemset.UpdateExampleResp
	UpdateHintReq              = problemset.UpdateHintReq
	UpdateHintResp             = problemset.UpdateHintResp
	UpdateJudgeDataReq         = problemset.UpdateJudgeDataReq
	UpdateJudgeDataResp        = problemset.UpdateJudgeDataResp
	UpdateLanguageReq          = problemset.UpdateLanguageReq
	UpdateLanguageResp         = problemset.UpdateLanguageResp
	UpdateProblemReq           = problemset.UpdateProblemReq
	UpdateProblemResp          = problemset.UpdateProblemResp
	UpdateTagReq               = problemset.UpdateTagReq
	UpdateTagResp              = problemset.UpdateTagResp

	Hint interface {
		// 添加提示
		AddHint(ctx context.Context, opts ...grpc.CallOption) (problemset.Hint_AddHintClient, error)
		// 删除提示
		DeleteHint(ctx context.Context, in *DeleteHintReq, opts ...grpc.CallOption) (*DeleteHintResp, error)
		// 修改提示
		UpdateHint(ctx context.Context, opts ...grpc.CallOption) (problemset.Hint_UpdateHintClient, error)
		// 获取提示
		GetHint(ctx context.Context, in *GetHintReq, opts ...grpc.CallOption) (problemset.Hint_GetHintClient, error)
		// 获取题目所有提示
		GetProblemHints(ctx context.Context, in *GetProblemHintsReq, opts ...grpc.CallOption) (problemset.Hint_GetProblemHintsClient, error)
	}

	defaultHint struct {
		cli zrpc.Client
	}
)

func NewHint(cli zrpc.Client) Hint {
	return &defaultHint{
		cli: cli,
	}
}

// 添加提示
func (m *defaultHint) AddHint(ctx context.Context, opts ...grpc.CallOption) (problemset.Hint_AddHintClient, error) {
	client := problemset.NewHintClient(m.cli.Conn())
	return client.AddHint(ctx, opts...)
}

// 删除提示
func (m *defaultHint) DeleteHint(ctx context.Context, in *DeleteHintReq, opts ...grpc.CallOption) (*DeleteHintResp, error) {
	client := problemset.NewHintClient(m.cli.Conn())
	return client.DeleteHint(ctx, in, opts...)
}

// 修改提示
func (m *defaultHint) UpdateHint(ctx context.Context, opts ...grpc.CallOption) (problemset.Hint_UpdateHintClient, error) {
	client := problemset.NewHintClient(m.cli.Conn())
	return client.UpdateHint(ctx, opts...)
}

// 获取提示
func (m *defaultHint) GetHint(ctx context.Context, in *GetHintReq, opts ...grpc.CallOption) (problemset.Hint_GetHintClient, error) {
	client := problemset.NewHintClient(m.cli.Conn())
	return client.GetHint(ctx, in, opts...)
}

// 获取题目所有提示
func (m *defaultHint) GetProblemHints(ctx context.Context, in *GetProblemHintsReq, opts ...grpc.CallOption) (problemset.Hint_GetProblemHintsClient, error) {
	client := problemset.NewHintClient(m.cli.Conn())
	return client.GetProblemHints(ctx, in, opts...)
}
