// Code generated by goctl. DO NOT EDIT.
// Source: problemset.proto

package server

import (
	"context"

	"zerooj/service/problemset/internal/logic/submit"
	"zerooj/service/problemset/internal/svc"
	"zerooj/service/problemset/pb/problemset"
)

type SubmitServer struct {
	svcCtx *svc.ServiceContext
	problemset.UnimplementedSubmitServer
}

func NewSubmitServer(svcCtx *svc.ServiceContext) *SubmitServer {
	return &SubmitServer{
		svcCtx: svcCtx,
	}
}

// 用户提交代码
func (s *SubmitServer) SubmitCode(stream problemset.Submit_SubmitCodeServer) error {
	l := submitlogic.NewSubmitCodeLogic(stream.Context(), s.svcCtx)
	return l.SubmitCode(stream)
}

// 获取题目的提交数
func (s *SubmitServer) GetProblemSubmitCount(ctx context.Context, in *problemset.GetProblemSubmitCountReq) (*problemset.GetProblemSubmitCountResp, error) {
	l := submitlogic.NewGetProblemSubmitCountLogic(ctx, s.svcCtx)
	return l.GetProblemSubmitCount(in)
}

// 分页获取用户提交
func (s *SubmitServer) GetUserSubmit(in *problemset.GetUserSubmitReq, stream problemset.Submit_GetUserSubmitServer) error {
	l := submitlogic.NewGetUserSubmitLogic(stream.Context(), s.svcCtx)
	return l.GetUserSubmit(in, stream)
}

// 获取用户某一道题的全部提交
func (s *SubmitServer) GetUserProblemSubmit(in *problemset.GetUserProblemSubmitReq, stream problemset.Submit_GetUserProblemSubmitServer) error {
	l := submitlogic.NewGetUserProblemSubmitLogic(stream.Context(), s.svcCtx)
	return l.GetUserProblemSubmit(in, stream)
}

// 获取通过id提交记录
func (s *SubmitServer) GetSubmitById(in *problemset.GetSubmitByIdReq, stream problemset.Submit_GetSubmitByIdServer) error {
	l := submitlogic.NewGetSubmitByIdLogic(stream.Context(), s.svcCtx)
	return l.GetSubmitById(in, stream)
}
