// Code generated by goctl. DO NOT EDIT.
// Source: judge.proto

package judge

import (
	"context"

	"zerooj/service/judge/pb/judge"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	JudgeReq  = judge.JudgeReq
	JudgeResp = judge.JudgeResp

	Judge interface {
		// 测评
		Judge(ctx context.Context, in *JudgeReq, opts ...grpc.CallOption) (*JudgeResp, error)
	}

	defaultJudge struct {
		cli zrpc.Client
	}
)

func NewJudge(cli zrpc.Client) Judge {
	return &defaultJudge{
		cli: cli,
	}
}

// 测评
func (m *defaultJudge) Judge(ctx context.Context, in *JudgeReq, opts ...grpc.CallOption) (*JudgeResp, error) {
	client := judge.NewJudgeClient(m.cli.Conn())
	return client.Judge(ctx, in, opts...)
}
