// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package other

import (
	"context"

	"zerooj/service/user/pb/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddCityReq                    = user.AddCityReq
	AddCityResp                   = user.AddCityResp
	AddSkillReq                   = user.AddSkillReq
	AddSkillResp                  = user.AddSkillResp
	AddUserPersonalWebsiteReq     = user.AddUserPersonalWebsiteReq
	AddUserPersonalWebsiteResp    = user.AddUserPersonalWebsiteResp
	AddUserSkillReq               = user.AddUserSkillReq
	AddUserSkillResp              = user.AddUserSkillResp
	City                          = user.City
	DeleteCityReq                 = user.DeleteCityReq
	DeleteCityResp                = user.DeleteCityResp
	DeleteSkillReq                = user.DeleteSkillReq
	DeleteSkillResp               = user.DeleteSkillResp
	DeleteUserPersonalWebsiteReq  = user.DeleteUserPersonalWebsiteReq
	DeleteUserPersonalWebsiteResp = user.DeleteUserPersonalWebsiteResp
	DeleteUserSkillReq            = user.DeleteUserSkillReq
	DeleteUserSkillResp           = user.DeleteUserSkillResp
	FollowUserInfo                = user.FollowUserInfo
	FollowUserReq                 = user.FollowUserReq
	FollowUserResp                = user.FollowUserResp
	ForgetPasswordReq             = user.ForgetPasswordReq
	ForgetPasswordResp            = user.ForgetPasswordResp
	GetBaseInfoReq                = user.GetBaseInfoReq
	GetBaseInfoResp               = user.GetBaseInfoResp
	GetFansReq                    = user.GetFansReq
	GetFansResp                   = user.GetFansResp
	GetFollowingsReq              = user.GetFollowingsReq
	GetFollowingsResp             = user.GetFollowingsResp
	GetPermissionReq              = user.GetPermissionReq
	GetPermissionResp             = user.GetPermissionResp
	GetUserInfoReq                = user.GetUserInfoReq
	GetUserInfoResp               = user.GetUserInfoResp
	MustDeleteCityReq             = user.MustDeleteCityReq
	MustDeleteCityResp            = user.MustDeleteCityResp
	MustDeleteSkillReq            = user.MustDeleteSkillReq
	MustDeleteSkillResp           = user.MustDeleteSkillResp
	PersonalWebsite               = user.PersonalWebsite
	Skill                         = user.Skill
	UpdateEmailReq                = user.UpdateEmailReq
	UpdateEmailResp               = user.UpdateEmailResp
	UpdatePasswordReq             = user.UpdatePasswordReq
	UpdatePasswordResp            = user.UpdatePasswordResp
	UpdatePermissionReq           = user.UpdatePermissionReq
	UpdatePermissionResp          = user.UpdatePermissionResp
	UpdateUserProfileReq          = user.UpdateUserProfileReq
	UpdateUserProfileResp         = user.UpdateUserProfileResp
	UpdateUsernameReq             = user.UpdateUsernameReq
	UpdateUsernameResp            = user.UpdateUsernameResp
	UserLoginReq                  = user.UserLoginReq
	UserLoginResp                 = user.UserLoginResp
	UserRegisterReq               = user.UserRegisterReq
	UserRegisterResp              = user.UserRegisterResp

	Other interface {
		// 添加和删除城市，只有客服能操作
		AddCity(ctx context.Context, in *AddCityReq, opts ...grpc.CallOption) (*AddCityResp, error)
		DeleteCity(ctx context.Context, in *DeleteCityReq, opts ...grpc.CallOption) (*DeleteCityResp, error)
		// 强行删除城市，必须要管理员权限
		MustDeleteCity(ctx context.Context, in *MustDeleteCityReq, opts ...grpc.CallOption) (*MustDeleteCityResp, error)
		// 添加和删除技能，只有客服能操作
		AddSkill(ctx context.Context, in *AddSkillReq, opts ...grpc.CallOption) (*AddSkillResp, error)
		DeleteSkill(ctx context.Context, in *DeleteSkillReq, opts ...grpc.CallOption) (*DeleteSkillResp, error)
		// 强行删除技能，必须要管理员权限
		MustDeleteSkill(ctx context.Context, in *MustDeleteSkillReq, opts ...grpc.CallOption) (*MustDeleteSkillResp, error)
	}

	defaultOther struct {
		cli zrpc.Client
	}
)

func NewOther(cli zrpc.Client) Other {
	return &defaultOther{
		cli: cli,
	}
}

// 添加和删除城市，只有客服能操作
func (m *defaultOther) AddCity(ctx context.Context, in *AddCityReq, opts ...grpc.CallOption) (*AddCityResp, error) {
	client := user.NewOtherClient(m.cli.Conn())
	return client.AddCity(ctx, in, opts...)
}

func (m *defaultOther) DeleteCity(ctx context.Context, in *DeleteCityReq, opts ...grpc.CallOption) (*DeleteCityResp, error) {
	client := user.NewOtherClient(m.cli.Conn())
	return client.DeleteCity(ctx, in, opts...)
}

// 强行删除城市，必须要管理员权限
func (m *defaultOther) MustDeleteCity(ctx context.Context, in *MustDeleteCityReq, opts ...grpc.CallOption) (*MustDeleteCityResp, error) {
	client := user.NewOtherClient(m.cli.Conn())
	return client.MustDeleteCity(ctx, in, opts...)
}

// 添加和删除技能，只有客服能操作
func (m *defaultOther) AddSkill(ctx context.Context, in *AddSkillReq, opts ...grpc.CallOption) (*AddSkillResp, error) {
	client := user.NewOtherClient(m.cli.Conn())
	return client.AddSkill(ctx, in, opts...)
}

func (m *defaultOther) DeleteSkill(ctx context.Context, in *DeleteSkillReq, opts ...grpc.CallOption) (*DeleteSkillResp, error) {
	client := user.NewOtherClient(m.cli.Conn())
	return client.DeleteSkill(ctx, in, opts...)
}

// 强行删除技能，必须要管理员权限
func (m *defaultOther) MustDeleteSkill(ctx context.Context, in *MustDeleteSkillReq, opts ...grpc.CallOption) (*MustDeleteSkillResp, error) {
	client := user.NewOtherClient(m.cli.Conn())
	return client.MustDeleteSkill(ctx, in, opts...)
}
