// Code generated by goctl. DO NOT EDIT.
// Source: problemset.proto

package server

import (
	"context"

	"zerooj/service/problemset/internal/logic/tag"
	"zerooj/service/problemset/internal/svc"
	"zerooj/service/problemset/pb/problemset"
)

type TagServer struct {
	svcCtx *svc.ServiceContext
	problemset.UnimplementedTagServer
}

func NewTagServer(svcCtx *svc.ServiceContext) *TagServer {
	return &TagServer{
		svcCtx: svcCtx,
	}
}

// 添加标签
func (s *TagServer) AddTag(ctx context.Context, in *problemset.AddTagReq) (*problemset.AddTagResp, error) {
	l := taglogic.NewAddTagLogic(ctx, s.svcCtx)
	return l.AddTag(in)
}

// 删除标签
func (s *TagServer) DeleteTag(ctx context.Context, in *problemset.DeleteTagReq) (*problemset.DeleteTagResp, error) {
	l := taglogic.NewDeleteTagLogic(ctx, s.svcCtx)
	return l.DeleteTag(in)
}

// 强行删除标签
func (s *TagServer) MustDeleteTag(ctx context.Context, in *problemset.MustDeleteTagReq) (*problemset.MustDeleteTagResp, error) {
	l := taglogic.NewMustDeleteTagLogic(ctx, s.svcCtx)
	return l.MustDeleteTag(in)
}

// 更新标签
func (s *TagServer) UpdateTag(ctx context.Context, in *problemset.UpdateTagReq) (*problemset.UpdateTagResp, error) {
	l := taglogic.NewUpdateTagLogic(ctx, s.svcCtx)
	return l.UpdateTag(in)
}

// 获取所有标签，可缓存
func (s *TagServer) GetAllTags(ctx context.Context, in *problemset.GetAllTagsReq) (*problemset.GetAllTagsResp, error) {
	l := taglogic.NewGetAllTagsLogic(ctx, s.svcCtx)
	return l.GetAllTags(in)
}

// 给题目添加标签，最多5个
func (s *TagServer) ProblemAddTags(ctx context.Context, in *problemset.ProblemAddTagsReq) (*problemset.ProblemAddTagsResp, error) {
	l := taglogic.NewProblemAddTagsLogic(ctx, s.svcCtx)
	return l.ProblemAddTags(in)
}

// 给题目删除标签
func (s *TagServer) ProblemDeleteTags(ctx context.Context, in *problemset.ProblemDeleteTagsReq) (*problemset.ProblemDeleteTagsResp, error) {
	l := taglogic.NewProblemDeleteTagsLogic(ctx, s.svcCtx)
	return l.ProblemDeleteTags(in)
}

// 获取一个题目的所有标签，可缓存
func (s *TagServer) GetProblemTags(ctx context.Context, in *problemset.GetProblemTagsReq) (*problemset.GetProblemTagsResp, error) {
	l := taglogic.NewGetProblemTagsLogic(ctx, s.svcCtx)
	return l.GetProblemTags(in)
}
