// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"zerooj/service/user/internal/logic/profile"
	"zerooj/service/user/internal/svc"
	"zerooj/service/user/pb/user"
)

type ProfileServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedProfileServer
}

func NewProfileServer(svcCtx *svc.ServiceContext) *ProfileServer {
	return &ProfileServer{
		svcCtx: svcCtx,
	}
}

// 获取用户简介
func (s *ProfileServer) GetUserProfile(ctx context.Context, in *user.GetUserProfileReq) (*user.GetUserProfileResp, error) {
	l := profilelogic.NewGetUserProfileLogic(ctx, s.svcCtx)
	return l.GetUserProfile(in)
}

// 修改用户简介，不包括个人网站和用户技能
func (s *ProfileServer) UpdateUserProfile(ctx context.Context, in *user.UpdateUserProfileReq) (*user.UpdateUserProfileResp, error) {
	l := profilelogic.NewUpdateUserProfileLogic(ctx, s.svcCtx)
	return l.UpdateUserProfile(in)
}

// 添加个人网站，最多5个
func (s *ProfileServer) AddUserPersonalWebsite(ctx context.Context, in *user.AddUserPersonalWebsiteReq) (*user.AddUserPersonalWebsiteResp, error) {
	l := profilelogic.NewAddUserPersonalWebsiteLogic(ctx, s.svcCtx)
	return l.AddUserPersonalWebsite(in)
}

// 删除个人网站
func (s *ProfileServer) DeleteUserPersonalWebsite(ctx context.Context, in *user.DeleteUserPersonalWebsiteReq) (*user.DeleteUserPersonalWebsiteResp, error) {
	l := profilelogic.NewDeleteUserPersonalWebsiteLogic(ctx, s.svcCtx)
	return l.DeleteUserPersonalWebsite(in)
}
