// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: mail.proto

package mail

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CheckCode_SendMailCheckCode_FullMethodName = "/mail.CheckCode/SendMailCheckCode"
)

// CheckCodeClient is the client API for CheckCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 邮件验证码
type CheckCodeClient interface {
	// 发送邮箱验证码
	SendMailCheckCode(ctx context.Context, in *SendMailCheckCodeReq, opts ...grpc.CallOption) (*SendMailCheckCodeResp, error)
}

type checkCodeClient struct {
	cc grpc.ClientConnInterface
}

func NewCheckCodeClient(cc grpc.ClientConnInterface) CheckCodeClient {
	return &checkCodeClient{cc}
}

func (c *checkCodeClient) SendMailCheckCode(ctx context.Context, in *SendMailCheckCodeReq, opts ...grpc.CallOption) (*SendMailCheckCodeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendMailCheckCodeResp)
	err := c.cc.Invoke(ctx, CheckCode_SendMailCheckCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CheckCodeServer is the server API for CheckCode service.
// All implementations must embed UnimplementedCheckCodeServer
// for forward compatibility
//
// 邮件验证码
type CheckCodeServer interface {
	// 发送邮箱验证码
	SendMailCheckCode(context.Context, *SendMailCheckCodeReq) (*SendMailCheckCodeResp, error)
	mustEmbedUnimplementedCheckCodeServer()
}

// UnimplementedCheckCodeServer must be embedded to have forward compatible implementations.
type UnimplementedCheckCodeServer struct {
}

func (UnimplementedCheckCodeServer) SendMailCheckCode(context.Context, *SendMailCheckCodeReq) (*SendMailCheckCodeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMailCheckCode not implemented")
}
func (UnimplementedCheckCodeServer) mustEmbedUnimplementedCheckCodeServer() {}

// UnsafeCheckCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CheckCodeServer will
// result in compilation errors.
type UnsafeCheckCodeServer interface {
	mustEmbedUnimplementedCheckCodeServer()
}

func RegisterCheckCodeServer(s grpc.ServiceRegistrar, srv CheckCodeServer) {
	s.RegisterService(&CheckCode_ServiceDesc, srv)
}

func _CheckCode_SendMailCheckCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMailCheckCodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CheckCodeServer).SendMailCheckCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CheckCode_SendMailCheckCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CheckCodeServer).SendMailCheckCode(ctx, req.(*SendMailCheckCodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// CheckCode_ServiceDesc is the grpc.ServiceDesc for CheckCode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CheckCode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mail.CheckCode",
	HandlerType: (*CheckCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMailCheckCode",
			Handler:    _CheckCode_SendMailCheckCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mail.proto",
}
