// Code generated by goctl. DO NOT EDIT.
// Source: problemset.proto

package server

import (
	"context"

	"zerooj/service/problemset/internal/logic/judgedata"
	"zerooj/service/problemset/internal/svc"
	"zerooj/service/problemset/pb/problemset"
)

type JudgeDataServer struct {
	svcCtx *svc.ServiceContext
	problemset.UnimplementedJudgeDataServer
}

func NewJudgeDataServer(svcCtx *svc.ServiceContext) *JudgeDataServer {
	return &JudgeDataServer{
		svcCtx: svcCtx,
	}
}

// 添加测评数据，客服权限
func (s *JudgeDataServer) AddJudgeData(ctx context.Context, in *problemset.AddJudgeDataReq) (*problemset.AddJudgeDataResp, error) {
	l := judgedatalogic.NewAddJudgeDataLogic(ctx, s.svcCtx)
	return l.AddJudgeData(in)
}

// 删除测评数据，客服权限
func (s *JudgeDataServer) DeleteJudgeData(ctx context.Context, in *problemset.DeleteJudgeDataReq) (*problemset.DeleteJudgeDataResp, error) {
	l := judgedatalogic.NewDeleteJudgeDataLogic(ctx, s.svcCtx)
	return l.DeleteJudgeData(in)
}

// 修改测评数据，客服权限
func (s *JudgeDataServer) UpdateJudgeData(ctx context.Context, in *problemset.UpdateJudgeDataReq) (*problemset.UpdateJudgeDataResp, error) {
	l := judgedatalogic.NewUpdateJudgeDataLogic(ctx, s.svcCtx)
	return l.UpdateJudgeData(in)
}

// 获取题目的测评数据，返回minio对象名称，可缓存
func (s *JudgeDataServer) GetJudgeData(ctx context.Context, in *problemset.GetJudgeDataReq) (*problemset.GetJudgeDataResp, error) {
	l := judgedatalogic.NewGetJudgeDataLogic(ctx, s.svcCtx)
	return l.GetJudgeData(in)
}
