// Code generated by goctl. DO NOT EDIT.
// Source: problemset.proto

package server

import (
	"context"

	"zerooj/service/problemset/internal/logic/judgedata"
	"zerooj/service/problemset/internal/svc"
	"zerooj/service/problemset/pb/problemset"
)

type JudgeDataServer struct {
	svcCtx *svc.ServiceContext
	problemset.UnimplementedJudgeDataServer
}

func NewJudgeDataServer(svcCtx *svc.ServiceContext) *JudgeDataServer {
	return &JudgeDataServer{
		svcCtx: svcCtx,
	}
}

// 添加测评数据
func (s *JudgeDataServer) AddJudgeData(stream problemset.JudgeData_AddJudgeDataServer) error {
	l := judgedatalogic.NewAddJudgeDataLogic(stream.Context(), s.svcCtx)
	return l.AddJudgeData(stream)
}

// 删除测评数据
func (s *JudgeDataServer) DeleteJudgeData(ctx context.Context, in *problemset.DeleteJudgeDataReq) (*problemset.DeleteJudgeDataResp, error) {
	l := judgedatalogic.NewDeleteJudgeDataLogic(ctx, s.svcCtx)
	return l.DeleteJudgeData(in)
}

// 修改测评数据
func (s *JudgeDataServer) UpdateJudgeData(stream problemset.JudgeData_UpdateJudgeDataServer) error {
	l := judgedatalogic.NewUpdateJudgeDataLogic(stream.Context(), s.svcCtx)
	return l.UpdateJudgeData(stream)
}

// 获取题目的测评数据，返回minio对象名称，可缓存
func (s *JudgeDataServer) GetJudgeData(in *problemset.GetJudgeDataReq, stream problemset.JudgeData_GetJudgeDataServer) error {
	l := judgedatalogic.NewGetJudgeDataLogic(stream.Context(), s.svcCtx)
	return l.GetJudgeData(in, stream)
}
