// Code generated by goctl. DO NOT EDIT.
// Source: mail.proto

package server

import (
	"context"

	"zerooj/service/mail/internal/logic/checkcode"
	"zerooj/service/mail/internal/svc"
	"zerooj/service/mail/pb/mail"
)

type CheckCodeServer struct {
	svcCtx *svc.ServiceContext
	mail.UnimplementedCheckCodeServer
}

func NewCheckCodeServer(svcCtx *svc.ServiceContext) *CheckCodeServer {
	return &CheckCodeServer{
		svcCtx: svcCtx,
	}
}

// 发送邮箱验证码
func (s *CheckCodeServer) SendMailCheckCode(ctx context.Context, in *mail.SendMailCheckCodeReq) (*mail.SendMailCheckCodeResp, error) {
	l := checkcodelogic.NewSendMailCheckCodeLogic(ctx, s.svcCtx)
	return l.SendMailCheckCode(in)
}
